export const API=import.meta.env.VITE_API_URL||(location.hostname==='127.0.0.1'||location.hostname==='localhost'?'http://127.0.0.1:8788':'https://customer-boardroom.vercel.app');
export class RoomClient{
 constructor(onState,onStatus){this.onState=onState;this.onStatus=onStatus;this.snapshot=null;this.credential=null;this.ws=null;this.timer=null;this.heartbeat=null;this.retry=0;this.epoch=0;this.pending=false;this.connected=false;this.invites=[];}
 async request(path,body,auth=true){const r=await fetch(API+path,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(auth&&this.credential?{Authorization:'Bearer '+this.credential.token}:{})},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store'});const data=await r.json();if(!r.ok){if(data.snapshot)this.update(data.snapshot);const e=new Error(data.error||'Connection failed.');e.status=r.status;throw e;}if(data.invites)this.invites=data.invites;return data;}
 update(s){if(this.snapshot&&s.revision<this.snapshot.revision)return;this.snapshot=s;this.onState(s);}
 async enter(code,name,invite){const resumeToken=crypto.randomUUID()+crypto.randomUUID();if(code)localStorage.setItem('boardroom:'+code,JSON.stringify({code,token:resumeToken}));let data;try{data=code?await this.request('/rooms/'+code+'/join',{name,resumeToken,...(invite?{invite}:{})},false):await this.request('/rooms',{},false);}catch(e){if(code&&e.status)localStorage.removeItem('boardroom:'+code);throw e;}this.credential={code:data.snapshot.code,token:data.token,id:data.id};localStorage.setItem('boardroom:'+this.credential.code,JSON.stringify(this.credential));localStorage.setItem('boardroom:last',this.credential.code);this.update(data.snapshot);await this.connect();return this.credential.code;}
 async restore(code){const raw=localStorage.getItem('boardroom:'+code);if(!raw)return false;try{this.credential=JSON.parse(raw);await this.refresh();await this.connect();return true;}catch(e){this.credential=null;throw e;}}
 async refresh(){const d=await this.request('/rooms/'+this.credential.code+'/snapshot');this.update(d.snapshot);}
 async connect(){this.consume();}
 async consume(){const epoch=++this.epoch;clearTimeout(this.timer);this.stream?.abort();const controller=this.stream=new AbortController();this.connected=false;this.onStatus('Connecting…');if(!navigator.onLine){this.onStatus('Offline · reconnect when online');return;}let watchdog;
 try{const r=await fetch(API+'/rooms/'+this.credential.code+'/events',{headers:{Authorization:'Bearer '+this.credential.token},signal:controller.signal,cache:'no-store'});if(!r.ok)throw Error('Live connection unavailable.');if(epoch!==this.epoch)return;this.connected=true;this.retry=0;this.onStatus('Live');const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='',last=Date.now();watchdog=setInterval(()=>{if(Date.now()-last>45000)controller.abort();},15000);while(true){const {done,value}=await reader.read();if(done||epoch!==this.epoch)break;last=Date.now();buffer+=decoder.decode(value,{stream:true});let split;while((split=buffer.indexOf('\n\n'))!==-1){const packet=buffer.slice(0,split);buffer=buffer.slice(split+2);const line=packet.split('\n').find(l=>l.startsWith('data: '));if(line){const d=JSON.parse(line.slice(6));if(d.snapshot)this.update(d.snapshot);}}}}catch{}finally{clearInterval(watchdog);if(epoch===this.epoch){this.connected=false;this.onStatus(navigator.onLine?'Reconnecting…':'Offline · reconnect when online');if(navigator.onLine)this.timer=setTimeout(()=>this.connect(),Math.min(10000,500*2**this.retry++)+Math.random()*300);}}
 }
 async act(type,payload={}){if(this.pending)throw new Error('Please wait for your previous action.');if(!navigator.onLine)throw new Error('You are offline. Reconnect before continuing.');this.pending=true;const clientActionId=crypto.randomUUID();try{for(let attempt=0;attempt<12;attempt++){try{const d=await this.request('/rooms/'+this.credential.code+'/actions',{type,payload,expectedRevision:this.snapshot.revision,clientActionId});this.update(d.snapshot);return d.snapshot;}catch(e){if(e.status===409){await new Promise(r=>setTimeout(r,50+Math.random()*120));continue;}if(!e.status&&attempt<2){await new Promise(r=>setTimeout(r,500));continue;}throw e;}}throw new Error('The room is busy. Please try again.');}finally{this.pending=false;}}
 disconnect(){this.epoch++;this.stream?.abort();clearTimeout(this.timer);this.connected=false;}
}
